[tool.isort]
src_paths = ["**"]
line_length = 60
multi_line_output = 3
include_trailing_comma = true
import_heading_future = "Future"
import_heading_stdlib = "Standard Library"
import_heading_thirdparty = "Third-Party"
import_heading_firstparty = "First-Party"
import_heading_localfolder = "Local Folder"