[tool.isort]
src_paths = ["**"]
line_length = 60
multi_line_output = 3
include_trailing_comma = true
import_heading_future = "Future"
import_heading_stdlib = "Standard Library"
import_heading_thirdparty = "Third-Party"
import_heading_firstparty = "First-Party"
import_heading_localfolder = "Local Folder"


[tool.pytest.ini_options]
testpaths = "tests"
required_plugins = ["pytest-cov"]
addopts = "--pdb --cov --cov-report html --strict-markers"
# log_cli = true                                       # Logs everything, not only on fail
log_cli_level = "DEBUG"
# log_cli_level = "INFO"
filterwarnings = [
    # note the use of single quote below to denote "raw" strings in TOML
    'ignore:invalid escape sequence \B:DeprecationWarning',
]
markers = ["incremental"]

[tool.coverage.run]
branch = true
source = ["src/sender", "src/common", "tests/sender/latex_print"]
plugins = ["coverage_conditional_plugin"]
dynamic_context = "test_function"

[tool.coverage.report]
# skip_covered = true
skip_empty = true
show_missing = true

[tool.coverage.html]
show_contexts = true

[tool.coverage.coverage_conditional_plugin.rules]
linux = "sys_platform == 'linux'"
win32 = "sys_platform == 'win32'"
