#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.1
#  in conjunction with Tcl version 8.6
#    May 20, 2021 04:07:12 AM CEST  platform: Windows NT

import sys
import tkinter.font as Tkfont

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import receiver_support
import os.path

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    top = Toplevel1 (root)
    receiver_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    receiver_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        # default_font = Tkfont.nametofont("TkDefaultFont")
        # default_font.configure(size=11)


        top.geometry("1308x878+306+92")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(0,  0)
        top.title("Träff display")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        """
            Shooter labels
        """


        self.shooter_lables = []
        self.Label_Shooter_Name = tk.Label(top, anchor='w')
        self.shooter_lables.append(self.Label_Shooter_Name)

        self.Label1 = tk.Label(top, anchor='w')
        self.shooter_lables.append(self.Label1)

        self.Label2 = tk.Label(top, anchor='w')
        self.shooter_lables.append(self.Label2)

        self.Label3 = tk.Label(top, anchor='w')
        self.shooter_lables.append(self.Label3)

        self.Label4 = tk.Label(top, anchor='w')
        self.shooter_lables.append(self.Label4)

        self.Label5 = tk.Label(top, anchor='w')
        self.shooter_lables.append(self.Label5)

        x = 20
        y = 60
        for labels in self.shooter_lables:
            labels.place(x=x, y=y, height=21, width=200)
            labels.configure(activebackground="#f9f9f9")
            labels.configure(activeforeground="black")
            labels.configure(background="#d9d9d9")
            labels.configure(disabledforeground="#a3a3a3")
            labels.configure(foreground="#000000")
            labels.configure(highlightbackground="#d9d9d9")
            labels.configure(highlightcolor="black")
            # labels.configure(text='''Label''')
            labels.configure(font=("Segoe UI", 13, "bold"))
            y += 30

        """
            End of shooter labels
        """

        self.Listbox1 = tk.Listbox(top)
        self.Listbox1.place(x=10, y=450, height=400, width=300)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(disabledforeground="#a3a3a3")
        self.Listbox1.configure(font="TkFixedFont")
        self.Listbox1.configure(foreground="#000000")
        self.Listbox1.configure(highlightbackground="#d9d9d9")
        self.Listbox1.configure(highlightcolor="black")
        self.Listbox1.configure(selectbackground="blue")
        self.Listbox1.configure(selectforeground="white")
        self.Listbox1.configure(font=("Segoe UI", 14))
        self.Listbox1.configure(takefocus="0")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(x=330, y=20, height=830, width=949)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Image = tk.Label(self.Frame1)
        self.Image.place(x=9, y=8, height=814, width=931)
        # self.Image.configure(activebackground="#f9f9f9")
        # self.Image.configure(activeforeground="black")
        # self.Image.configure(background="#d9d9d9")
        # self.Image.configure(disabledforeground="#a3a3a3")
        # self.Image.configure(foreground="#000000")
        # self.Image.configure(highlightbackground="#d9d9d9")
        # self.Image.configure(highlightcolor="black")
        self.Image.configure(text='''Bild''')

if __name__ == '__main__':
    vp_start_gui()





