#############################################################################
# Generated by PAGE version 6.1
#  in conjunction with Tcl version 8.6
#  May 31, 2021 02:49:42 PM CEST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
}



    menu .pop47 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 1 
    vTcl:DefineAlias ".pop47" "Popupmenu1" vTcl:WidgetProc "" 1
    menu .pop49 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 1 
    vTcl:DefineAlias ".pop49" "Popupmenu2" vTcl:WidgetProc "" 1
    menu .pop50 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 1 
    vTcl:DefineAlias ".pop50" "Popupmenu3" vTcl:WidgetProc "" 1

proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m45" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 800x380+300+146
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1920 1080
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Träffmarkerare"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    message $top.mes46 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -takefocus {} -text Namn: -width 60 
    vTcl:DefineAlias "$top.mes46" "Message1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra47 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 395 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 515 
    vTcl:DefineAlias "$top.fra47" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra47
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Bild 
    vTcl:DefineAlias "$site_3_0.lab48" "Label1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab48
    place $site_3_0.lab48 \
        -in $site_3_0 -x 10 -y 10 -width 495 -relwidth 0 -height 375 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.fra47
    entry $top.ent49 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify center -selectbackground blue \
        -selectforeground white -width 64 
    vTcl:DefineAlias "$top.ent49" "Entry_Point" vTcl:WidgetProc "Toplevel1" 1
    bind $top.ent49 <Key-Return> {
        point_entry
    }
    entry $top.ent50 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify center -selectbackground blue \
        -selectforeground white -width 64 
    vTcl:DefineAlias "$top.ent50" "Entry_Clock" vTcl:WidgetProc "Toplevel1" 1
    bind $top.ent50 <Key-Return> {
        clock_entry
    }
    message $top.mes51 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Poäng -width 60 
    vTcl:DefineAlias "$top.mes51" "Message2" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes52 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Klocka -width 60 
    vTcl:DefineAlias "$top.mes52" "Message3" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $top.rad53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command allow_entry \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -takefocus 0 -text Stilla -value 1 
    vTcl:DefineAlias "$top.rad53" "Radiobutton1" vTcl:WidgetProc "Toplevel1" 1
    bind $top.rad53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Stillastående}
    }
    radiobutton $top.rad54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command allow_entry \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -takefocus 0 -text Jaktskott -value 2 
    vTcl:DefineAlias "$top.rad54" "Radiobutton2" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $top.rad55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command allow_entry \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -takefocus 0 -text Löpande -value 3 
    vTcl:DefineAlias "$top.rad55" "Radiobutton3" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $top.rad56 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command allow_entry \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -takefocus 0 -text Dubble -value 4 
    vTcl:DefineAlias "$top.rad56" "Radiobutton4" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo52 \
        -values {{Per Persson} {Johan Johansson} {Sven Svensson} {}} \
        -state readonly -foreground {} -background {} -takefocus 0 
    vTcl:DefineAlias "$top.tCo52" "TCombobox1" vTcl:WidgetProc "Toplevel1" 1
    bind $top.tCo52 <FocusIn> {
        _from_combobox
    }
    listbox $top.lis45 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -height 102 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground blue -selectforeground white -takefocus 0 \
        -width 184 
    $top.lis45 configure -font "TkFixedFont"
    $top.lis45 insert end text
    vTcl:DefineAlias "$top.lis45" "Listbox1" vTcl:WidgetProc "Toplevel1" 1
    bind $top.lis45 <Key-BackSpace> {
        delete_item
    }
    bind $top.lis45 <Key-Delete> {
        delete_item
    }
    label $top.lab45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ff0000 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text Invalid 
    vTcl:DefineAlias "$top.lab45" "Label_PointError" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ff0000 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text Invalid 
    vTcl:DefineAlias "$top.lab46" "Label_ClockError" vTcl:WidgetProc "Toplevel1" 1
    button $top.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command update_img \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Update Img} 
    vTcl:DefineAlias "$top.but45" "Button_UpdateImg" vTcl:WidgetProc "Toplevel1" 1
    button $top.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command destroy_window \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Exit 
    vTcl:DefineAlias "$top.but46" "Exit" vTcl:WidgetProc "Toplevel1" 1
    menu $top.m45 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    $top.m45 add cascade \
        -menu "$top.m45.men45" -command {{}} -label Inställningar 
    set site_3_0 $top.m45
    menu $site_3_0.men45 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    $site_3_0.men45 add checkbutton \
        -variable free_mode_check -command {#free_mode} \
        -label {Fritt läge [Experimentell]} 
    $top.m45 add command \
        -command {#open_print_window} -label {Skriv ut} 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.mes46 \
        -in $top -x 30 -y 20 -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x 250 -y 0 -width 515 -relwidth 0 -height 395 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent49 \
        -in $top -x 40 -y 170 -width 64 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent50 \
        -in $top -x 140 -y 170 -width 64 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes51 \
        -in $top -x 50 -y 140 -anchor nw -bordermode ignore 
    place $top.mes52 \
        -in $top -x 150 -y 140 -anchor nw -bordermode ignore 
    place $top.rad53 \
        -in $top -x 40 -y 60 -anchor nw -bordermode ignore 
    place $top.rad54 \
        -in $top -x 40 -y 90 -anchor nw -bordermode ignore 
    place $top.rad55 \
        -in $top -x 140 -y 60 -anchor nw -bordermode ignore 
    place $top.rad56 \
        -in $top -x 140 -y 90 -anchor nw -bordermode ignore 
    place $top.tCo52 \
        -in $top -x 80 -y 20 -anchor nw -bordermode ignore 
    place $top.lis45 \
        -in $top -x 30 -y 230 -width 184 -relwidth 0 -height 102 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 40 -y 190 -width 64 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 140 -y 190 -width 64 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.but45 \
        -in $top -x 130 -y 350 -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 40 -y 350 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

